[project]
name = "akash-q3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gdsfactory>=9.43.0",
    "gdstk>=1.0.0",
    "pyaedt==0.24",
    "qfab",
    "scipy>=1.17.1",
]

[tool.uv.sources]
qfab = { git = "https://github.com/qnl/qfab.git", branch = "gdsfactory9" }
